try {
  //...
  // lots of code
  //... 
} catch (AnException exception) {
  LogError("Unexpected exception");
}
